// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0KQTgN_2Q7_N6_ix9z6XT_-LYBoauMOI',
    appId: '1:399009485499:ios:c55b9d00c58c83e629cf9e',
    messagingSenderId: '399009485499',
    projectId: 'mpts-ims',
    storageBucket: 'mpts-ims.firebasestorage.app',
    iosBundleId: 'com.manoj.mptIms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMhCQ0gLLEp5CbipY5DnqIn3eC8HMrq2U',
    appId: '1:399009485499:web:56819193de58514829cf9e',
    messagingSenderId: '399009485499',
    projectId: 'mpts-ims',
    authDomain: 'mpts-ims.firebaseapp.com',
    storageBucket: 'mpts-ims.firebasestorage.app',
    measurementId: 'G-6WD7NK6MJ3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMhCQ0gLLEp5CbipY5DnqIn3eC8HMrq2U',
    appId: '1:399009485499:web:c5838ea52a622be029cf9e',
    messagingSenderId: '399009485499',
    projectId: 'mpts-ims',
    authDomain: 'mpts-ims.firebaseapp.com',
    storageBucket: 'mpts-ims.firebasestorage.app',
    measurementId: 'G-EPR2PP47ZC',
  );

}